// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messageprotocol.proto

package com.holelin.messageserver.protocol;

public final class MessageProtocol {
  private MessageProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.MessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息的唯一Id可以用 UUID 表示
     * </pre>
     *
     * <code>string messageId = 1;</code>
     * @return The messageId.
     */
    String getMessageId();
    /**
     * <pre>
     * 消息的唯一Id可以用 UUID 表示
     * </pre>
     *
     * <code>string messageId = 1;</code>
     * @return The bytes for messageId.
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     * 消息发送方
     * </pre>
     *
     * <code>string fromUid = 2;</code>
     * @return The fromUid.
     */
    String getFromUid();
    /**
     * <pre>
     * 消息发送方
     * </pre>
     *
     * <code>string fromUid = 2;</code>
     * @return The bytes for fromUid.
     */
    com.google.protobuf.ByteString
        getFromUidBytes();

    /**
     * <pre>
     * 消息接收方
     * </pre>
     *
     * <code>string sendUid = 3;</code>
     * @return The sendUid.
     */
    String getSendUid();
    /**
     * <pre>
     * 消息接收方
     * </pre>
     *
     * <code>string sendUid = 3;</code>
     * @return The bytes for sendUid.
     */
    com.google.protobuf.ByteString
        getSendUidBytes();

    /**
     * <pre>
     * 聊天模式 群聊还是单聊
     * </pre>
     *
     * <code>int32 chatType = 4;</code>
     * @return The chatType.
     */
    int getChatType();

    /**
     * <pre>
     * 消息类型 比如登录消息、聊天消息、ack 消息、ping、pong 消息
     * </pre>
     *
     * <code>int32 messageType = 5;</code>
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <pre>
     * 消息格式 如文本 图片等
     * </pre>
     *
     * <code>int32 messageFormat = 6;</code>
     * @return The messageFormat.
     */
    int getMessageFormat();

    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 发送消息的时间戳
     * </pre>
     *
     * <code>int64 timestamp = 8;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * 消息格式
   * </pre>
   *
   * Protobuf type {@code protocol.MessageProto}
   */
  public static final class MessageProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.MessageProto)
      MessageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageProto.newBuilder() to construct.
    private MessageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageProto() {
      messageId_ = "";
      fromUid_ = "";
      sendUid_ = "";
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageProto();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtocol.internal_static_protocol_MessageProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtocol.internal_static_protocol_MessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProto.class, Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object messageId_ = "";
    /**
     * <pre>
     * 消息的唯一Id可以用 UUID 表示
     * </pre>
     *
     * <code>string messageId = 1;</code>
     * @return The messageId.
     */
    @Override
    public String getMessageId() {
      Object ref = messageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息的唯一Id可以用 UUID 表示
     * </pre>
     *
     * <code>string messageId = 1;</code>
     * @return The bytes for messageId.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object fromUid_ = "";
    /**
     * <pre>
     * 消息发送方
     * </pre>
     *
     * <code>string fromUid = 2;</code>
     * @return The fromUid.
     */
    @Override
    public String getFromUid() {
      Object ref = fromUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息发送方
     * </pre>
     *
     * <code>string fromUid = 2;</code>
     * @return The bytes for fromUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      Object ref = fromUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDUID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object sendUid_ = "";
    /**
     * <pre>
     * 消息接收方
     * </pre>
     *
     * <code>string sendUid = 3;</code>
     * @return The sendUid.
     */
    @Override
    public String getSendUid() {
      Object ref = sendUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sendUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息接收方
     * </pre>
     *
     * <code>string sendUid = 3;</code>
     * @return The bytes for sendUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getSendUidBytes() {
      Object ref = sendUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sendUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHATTYPE_FIELD_NUMBER = 4;
    private int chatType_ = 0;
    /**
     * <pre>
     * 聊天模式 群聊还是单聊
     * </pre>
     *
     * <code>int32 chatType = 4;</code>
     * @return The chatType.
     */
    @Override
    public int getChatType() {
      return chatType_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 5;
    private int messageType_ = 0;
    /**
     * <pre>
     * 消息类型 比如登录消息、聊天消息、ack 消息、ping、pong 消息
     * </pre>
     *
     * <code>int32 messageType = 5;</code>
     * @return The messageType.
     */
    @Override
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGEFORMAT_FIELD_NUMBER = 6;
    private int messageFormat_ = 0;
    /**
     * <pre>
     * 消息格式 如文本 图片等
     * </pre>
     *
     * <code>int32 messageFormat = 6;</code>
     * @return The messageFormat.
     */
    @Override
    public int getMessageFormat() {
      return messageFormat_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object content_ = "";
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * 发送消息的时间戳
     * </pre>
     *
     * <code>int64 timestamp = 8;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fromUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sendUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sendUid_);
      }
      if (chatType_ != 0) {
        output.writeInt32(4, chatType_);
      }
      if (messageType_ != 0) {
        output.writeInt32(5, messageType_);
      }
      if (messageFormat_ != 0) {
        output.writeInt32(6, messageFormat_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(8, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fromUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sendUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sendUid_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chatType_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, messageType_);
      }
      if (messageFormat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, messageFormat_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageProto)) {
        return super.equals(obj);
      }
      MessageProto other = (MessageProto) obj;

      if (!getMessageId()
          .equals(other.getMessageId())) return false;
      if (!getFromUid()
          .equals(other.getFromUid())) return false;
      if (!getSendUid()
          .equals(other.getSendUid())) return false;
      if (getChatType()
          != other.getChatType()) return false;
      if (getMessageType()
          != other.getMessageType()) return false;
      if (getMessageFormat()
          != other.getMessageFormat()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + FROMUID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUid().hashCode();
      hash = (37 * hash) + SENDUID_FIELD_NUMBER;
      hash = (53 * hash) + getSendUid().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + MESSAGEFORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageFormat();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * Protobuf type {@code protocol.MessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.MessageProto)
        MessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtocol.internal_static_protocol_MessageProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtocol.internal_static_protocol_MessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.class, Builder.class);
      }

      // Construct using cn.holelin.messagepushnetty.protocol.MessageProtocol.MessageProto.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messageId_ = "";
        fromUid_ = "";
        sendUid_ = "";
        chatType_ = 0;
        messageType_ = 0;
        messageFormat_ = 0;
        content_ = "";
        timestamp_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtocol.internal_static_protocol_MessageProto_descriptor;
      }

      @Override
      public MessageProto getDefaultInstanceForType() {
        return MessageProto.getDefaultInstance();
      }

      @Override
      public MessageProto build() {
        MessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageProto buildPartial() {
        MessageProto result = new MessageProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MessageProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.messageId_ = messageId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fromUid_ = fromUid_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sendUid_ = sendUid_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.chatType_ = chatType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.messageFormat_ = messageFormat_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProto) {
          return mergeFrom((MessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProto other) {
        if (other == MessageProto.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFromUid().isEmpty()) {
          fromUid_ = other.fromUid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getSendUid().isEmpty()) {
          sendUid_ = other.sendUid_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getMessageFormat() != 0) {
          setMessageFormat(other.getMessageFormat());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                messageId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                fromUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                sendUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                chatType_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                messageType_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                messageFormat_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object messageId_ = "";
      /**
       * <pre>
       * 消息的唯一Id可以用 UUID 表示
       * </pre>
       *
       * <code>string messageId = 1;</code>
       * @return The messageId.
       */
      public String getMessageId() {
        Object ref = messageId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息的唯一Id可以用 UUID 表示
       * </pre>
       *
       * <code>string messageId = 1;</code>
       * @return The bytes for messageId.
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息的唯一Id可以用 UUID 表示
       * </pre>
       *
       * <code>string messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        messageId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的唯一Id可以用 UUID 表示
       * </pre>
       *
       * <code>string messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        messageId_ = getDefaultInstance().getMessageId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的唯一Id可以用 UUID 表示
       * </pre>
       *
       * <code>string messageId = 1;</code>
       * @param value The bytes for messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object fromUid_ = "";
      /**
       * <pre>
       * 消息发送方
       * </pre>
       *
       * <code>string fromUid = 2;</code>
       * @return The fromUid.
       */
      public String getFromUid() {
        Object ref = fromUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息发送方
       * </pre>
       *
       * <code>string fromUid = 2;</code>
       * @return The bytes for fromUid.
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        Object ref = fromUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息发送方
       * </pre>
       *
       * <code>string fromUid = 2;</code>
       * @param value The fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        fromUid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息发送方
       * </pre>
       *
       * <code>string fromUid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUid() {
        fromUid_ = getDefaultInstance().getFromUid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息发送方
       * </pre>
       *
       * <code>string fromUid = 2;</code>
       * @param value The bytes for fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromUid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object sendUid_ = "";
      /**
       * <pre>
       * 消息接收方
       * </pre>
       *
       * <code>string sendUid = 3;</code>
       * @return The sendUid.
       */
      public String getSendUid() {
        Object ref = sendUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sendUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息接收方
       * </pre>
       *
       * <code>string sendUid = 3;</code>
       * @return The bytes for sendUid.
       */
      public com.google.protobuf.ByteString
          getSendUidBytes() {
        Object ref = sendUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sendUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息接收方
       * </pre>
       *
       * <code>string sendUid = 3;</code>
       * @param value The sendUid to set.
       * @return This builder for chaining.
       */
      public Builder setSendUid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        sendUid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息接收方
       * </pre>
       *
       * <code>string sendUid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUid() {
        sendUid_ = getDefaultInstance().getSendUid();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息接收方
       * </pre>
       *
       * <code>string sendUid = 3;</code>
       * @param value The bytes for sendUid to set.
       * @return This builder for chaining.
       */
      public Builder setSendUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sendUid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       * 聊天模式 群聊还是单聊
       * </pre>
       *
       * <code>int32 chatType = 4;</code>
       * @return The chatType.
       */
      @Override
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       * 聊天模式 群聊还是单聊
       * </pre>
       *
       * <code>int32 chatType = 4;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 聊天模式 群聊还是单聊
       * </pre>
       *
       * <code>int32 chatType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       * 消息类型 比如登录消息、聊天消息、ack 消息、ping、pong 消息
       * </pre>
       *
       * <code>int32 messageType = 5;</code>
       * @return The messageType.
       */
      @Override
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型 比如登录消息、聊天消息、ack 消息、ping、pong 消息
       * </pre>
       *
       * <code>int32 messageType = 5;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型 比如登录消息、聊天消息、ack 消息、ping、pong 消息
       * </pre>
       *
       * <code>int32 messageType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int messageFormat_ ;
      /**
       * <pre>
       * 消息格式 如文本 图片等
       * </pre>
       *
       * <code>int32 messageFormat = 6;</code>
       * @return The messageFormat.
       */
      @Override
      public int getMessageFormat() {
        return messageFormat_;
      }
      /**
       * <pre>
       * 消息格式 如文本 图片等
       * </pre>
       *
       * <code>int32 messageFormat = 6;</code>
       * @param value The messageFormat to set.
       * @return This builder for chaining.
       */
      public Builder setMessageFormat(int value) {
        
        messageFormat_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息格式 如文本 图片等
       * </pre>
       *
       * <code>int32 messageFormat = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageFormat() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageFormat_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 发送消息的时间戳
       * </pre>
       *
       * <code>int64 timestamp = 8;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 发送消息的时间戳
       * </pre>
       *
       * <code>int64 timestamp = 8;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送消息的时间戳
       * </pre>
       *
       * <code>int64 timestamp = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.MessageProto)
    }

    // @@protoc_insertion_point(class_scope:protocol.MessageProto)
    private static final MessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageProto();
    }

    public static MessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProto>
        PARSER = new com.google.protobuf.AbstractParser<MessageProto>() {
      @Override
      public MessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageProto> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_MessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_MessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025Messageprotocol.proto\022\010protocol\"\245\001\n\014Me" +
      "ssageProto\022\021\n\tmessageId\030\001 \001(\t\022\017\n\007fromUid" +
      "\030\002 \001(\t\022\017\n\007sendUid\030\003 \001(\t\022\020\n\010chatType\030\004 \001(" +
      "\005\022\023\n\013messageType\030\005 \001(\005\022\025\n\rmessageFormat\030" +
      "\006 \001(\005\022\017\n\007content\030\007 \001(\t\022\021\n\ttimestamp\030\010 \001(" +
      "\003B9\n$cn.holelin.messagepushnetty.protoco" +
      "lB\017MessageProtocolH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_MessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_MessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_MessageProto_descriptor,
        new String[] { "MessageId", "FromUid", "SendUid", "ChatType", "MessageType", "MessageFormat", "Content", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
