server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dicom?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: holelin..
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    sql-migration-prefix: DICOM_
    locations:
      - classpath:db/migration
    # 只要管理自己的数据库
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    create-schemas: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations:
    - classpath:/mapping/*Mapping.xml
